### ISSUE TITLE
Can't find tag pattern on Centos 6

### ISSUE THREAD

**Issue by zegervdv** [thinca/node-vimhelp#1]
I'm trying to run the hubot-vimhelp script on a Centos 6 machine, but it does't seem to find the help.

In hubot I got the following error:

~~~
vagrant> :help j
vagrant> E434: Can't find tag pattern
~~~

When trying the example on the README page in node I get this:
~~~
> const {VimHelp} = require("vimhelp");
undefined
> let vimHelp = new VimHelp();
undefined
> vimHelp.search("j").then((text) => {
...   console.log(text);
... });
Promise { <pending> }
> (node:2306) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
~~~

Vim is installed on the machine, and based on the error in hubot, it seems to find it.

**Comment by thinca** [comment]
I couldn't reproduce the problem.

What is your Vim's version?

Is Vim installed correctly?
Can you see the help of Vim when you use Vim directly?

**Comment by zegervdv** [comment]
I am using vim 8.
It does work when I run hubot under my own username, so maybe a .vimrc is required for it to work?

**Comment by thinca** [comment]
`.vimrc` is not required.

> I run hubot under my own username

Hmm, do you have two environment?
Maybe other Vim is used in each environment.
Could you try to specify `{vimBin}` argument to `new VimHelp()`?

```javascript
let vimHelp = new VimHelp('/path/to/vim');
```

**Comment by zegervdv** [comment]
I get the same error when specifying the path.

I have managed to get it to work with a .vimrc with only `set nocompatible` in it.
